apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-apache
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/SohailHanif/CCGC5504.git
    targetRevision: HEAD
    path: week_10/helm_apache
    helm: {} # optional: you can add valueFiles or values here
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true