apiVersion: v1
kind: Pod
metadata:
  name: basic-pods
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: alpine
      command: ["tail", "-f", "/dev/null"]