apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: guestbook-ui
  ports:
    - name: http
      port: 80          # Service’s internal port
      targetPort: 80    # Your container’s port
      nodePort: 30082  # host port