apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: default
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - name: http
      port: 80         # Service’s internal port
      targetPort: 80   # Your container’s port
      nodePort: 30083  # Host (AWS) port