name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: sohailhanif
      IMAGE_NAME: sohail-website
      IMAGE_TAG: $(date +%s)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: test print
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} ; echo $DOCKERHUB_USERNAME

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: $DOCKERHUB_USERNAME
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
